{% set name = "metomi-rose" %}
{% set version = "2.0b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc03758377303a2ac5c8c1828208a6283d638d24dc860d82fa598e8f9e8dfcf6

build:
  number: 0
  skip: true  # [py<37 or not unix]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - aiofiles
    - jinja2 >=2.10.1
    - ldap3
    - metomi-isodatetime
    - requests
    - sqlalchemy
    - tornado
    - psutil >=5.6.0

test:
  imports:
    - metomi.rose
    - metomi.rose.macro
  commands:
    - rose --version
    - PAGER=cat rose macro --help

about:
  home: https://github.com/metomi/rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'A toolkit for writing, editing and running application configurations.'
  doc_url: http://metomi.github.io/rose
  dev_url: https://github.com/metomi/rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - datamel
    - metronnie
