{% set name = "metomi-rose" %}
{% set version = "2.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d9cc2086b260d207d944ada67de5a78ee47f45525e7b7ab4c51fe47158eccf9

build:
  number: 0
  skip: true  # [py<37 or not unix]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - metomi.rose
    - metomi.rose.macro
  commands:
    - rose --version
    - PAGER=cat rose macro --help
    - rose resource syntax/rose-conf.lang  # test packaging of non-python files

outputs:
  # base package with only required dependencies
  - name: {{ name }}-base
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - python
      run:
        - aiofiles
        - jinja2 >=2.10.1
        - ldap3
        - metomi-isodatetime
        - psutil >=5.6.0
        - python
        - requests
        - sqlalchemy
        - setuptools
        # - tornado (rosie disco is temporally disabled)

  # "recommended" package
  # NOTE: currently the same as base
  # For the next release we should spin `rosa` and `rosie disco` out of this
  - name: {{ name }}
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage(name + "-base", exact=True) }}

about:
  home: https://github.com/metomi/rose
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: A toolkit for writing, editing and running application configurations.
  doc_url: http://metomi.github.io/rose
  dev_url: https://github.com/metomi/rose

extra:
  recipe-maintainers:
    - oliver-sanders
    - wxtim
    - datamel
    - metronnie
